// modules/custom/db_admin/src/AddFundingOrganization/src/app/funding-organization-form/funding-organization-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';

@Component({
  selector: 'icrp-funding-organization-form',
  templateUrl: './funding-organization-form.component.html',
  styleUrls: ['./funding-organization-form.component.css']
})
export class FundingOrganizationFormComponent implements OnInit {

  form: FormGroup;

  constructor(private formBuilder: FormBuilder) {
    this.form = this.createForm();
  }

  createForm(): FormGroup {
    return this.formBuilder.group({
      partner: ['', Validators.required],
      memberType: ['associate', Validators.required],
      name: '',
      abbreviation: '',
      organizationType: '',
      latitude: null,
      longitude: null,
      country: '',
      currency: '',
      note: '',
      annualizedFunding: false,
    });
  }

  ngOnInit() {
  }

}

<form [formGroup]="form">
  <div
    class="bordered padded form-group"
    fxLayout="row"
    fxLayout.lt-md="column"

    fxLayoutAlign="start center"
    fxLayoutAlign.lt-md="center start"
    fxLayoutGap="15px">
    <div
      fxFlex
      fxFlex.lt-md="nogrow"

      fxLayout="row"
      fxLayout.lt-md="column"

      fxLayoutAlign="start center"
      fxLayoutAlign.lt-md="center start"

      fxLayoutGap="10px"
      fxLayoutGap.lt-md="5px">
      <label
        class="inline nowrap"
        for="partner"
        fxFlex="15%"
        fxFlex.lt-md="nogrow">
        Partner <span class="text-danger">*</span>
      </label>
      <select
        fxFlex="85%"
        fxFlex.lt-md="nogrow"
        id="partner"
        name="partner"
        class="form-control"
        [formControl]="form.controls.partner">
        <option value="">Select a partner</option>
      </select>
    </div>

    <div
      fxFlex
      fxFlex.lt-md="nogrow"

      fxLayout="row"
      fxLayout.lt-md="column"

      fxLayoutAlign="start center"
      fxLayoutAlign.lt-md="center start"

      fxLayoutGap="10px"
      fxLayoutGap.lt-md="5px">
      <label class="inline" for="memberType">
        Member Type <span class="text-danger">*</span>
      </label>
      <input
        type="hidden"
        id="memberType"
        aria-label="This fieldset contains two radio buttons to select whether the chosen organization is a partner or an associate.">

      <label class="inline normal-weight" for="memberTypePartner">
        <input
          id="memberTypePartner"
          type="radio"
          name="memberType"
          value="partner"
          [formControl]="form.controls.memberType">
        Partner
      </label>

      <label class="inline normal-weight" for="memberTypeAssociate">
        <input
          id="memberTypeAssociate"
          type="radio"
          name="memberType"
          value="associate"
          [formControl]="form.controls.memberType">
        Associate
      </label>
    </div>
  </div>

  <div
    class="form-group"
    fxLayout="row"
    fxLayout.lt-md="column"
    fxLayoutGap="15px">
    <div fxFlex fxFlex.lt-md="nogrow">
      <label for="name">
        Name <span class="text-danger">*</span>
      </label>
      <input
        id="name"
        name="name"
        class="form-control"
        placeholder="Enter name of funding organization"
        [formControl]="form.controls.name">
    </div>

    <div fxFlex fxFlex.lt-md="nogrow">
      <label for="abbreviation">
        Abbreviation <span class="text-danger">*</span>
      </label>
      <input
        id="abbreviation"
        name="abbreviation"
        class="form-control"
        placeholder="Enter abbreviation for funding organization's name"
        [formControl]="form.controls.abbreviation">
    </div>
  </div>

  <div

    class="form-group"
    fxLayout="row-wrap"
    fxLayout.lt-md="column"
    fxLayoutGap="15px">
    <div fxFlex fxFlex.lt-md="nogrow">
      <label for="organizationType">
        Organization Type <span class="text-danger">*</span>
      </label>
      <select
        id="organizationType"
        name="organizationType"
        class="form-control"
        [formControl]="form.controls.organizationType">
        <option value="">Select an organization type</option>
      </select>
    </div>

    <div fxFlex fxFlex.lt-md="nogrow">
      <label for="mapCoordinates">Map Coordinates</label>
      <input
        type="hidden"
        id="mapCoordinates"
        aria-label="This fieldset contains two text input fields to enter the longitude and latitude of the funding organization.">

      <div
        fxLayout="row"
        fxLayout.lt-md="column"
        fxLayoutGap="15px"
        fxLayoutGap.lt-md="10px"
        >
        <input
          id="latitude"
          name="latitude"
          class="form-control"
          type="number"
          placeholder="Enter latitude"
          fxFlex
          fxFlex.lt-md="nogrow"
          [formControl]="form.controls.latitude">

        <input
          id="longitude"
          name="longitude"
          class="form-control"
          type="number"
          placeholder="Enter longitude"
          fxFlex
          fxFlex.lt-md="nogrow"
          [formControl]="form.controls.longitude">
      </div>
    </div>
  </div>


  <div
    class="form-group"
    fxLayout="row"
    fxLayout.lt-md="column"
    fxLayoutGap="15px"
  >
    <div fxFlex fxFlex.lt-md="nogrow">
      <label for="country">
        Country <span class="text-danger">*</span>
      </label>
      <select
        id="country"
        name="country"
        class="form-control"
        [formControl]="form.controls.country">
        <option value="">Select a country</option>
      </select>
    </div>

    <div fxFlex fxFlex.lt-md="nogrow">
      <label for="currency">
        Currency <span class="text-danger">*</span>
      </label>
      <select
        id="currency"
        name="currency"
        class="form-control"
        [formControl]="form.controls.currency">
        <option value="">Select a currency</option>
      </select>
    </div>
  </div>

  <div class="form-group">
      <label for="note">Note</label>
      <textarea
        id="note"
        name="note"
        class="form-control vertical-resize default-min-height"
        placeholder="Enter note (optional)"
        rows="3"
        [formControl]="form.controls.note">
      ></textarea>
  </div>

  <div
    class="form-group"
    fxLayout="row"
    fxLayoutWrap
    fxLayoutAlign="space-between center"
    fxLayoutGap="15px">
    <label class="inline" for="annualizedFunding">
      <input
        id="annualizedFunding"
        type="checkbox"
        name="annualizedFunding"
        [formControl]="form.controls.annualizedFunding">
      Annualized Funding
    </label>

    <i class="text-muted">* indicates required fields</i>
  </div>

  <div class="text-center vertical-margins">
    <button class="btn btn-primary">Save</button>
    <button class="btn btn-default">Cancel</button>
  </div>
</form>

<pre>{{form.value | json}}</pre>

// modules/custom/db_admin/src/React/add-funding-organization/src/components/FundingOrganizationForm/FundingOrganizationForm.js
import React from 'react';
import { Alert, Button, Checkbox, Col, Form, FormGroup, Grid, Radio, ControlLabel, FormControl, Row, HelpBlock } from 'react-bootstrap';
import Spinner from '../Spinner/';
import './FundingOrganizationForm.css';

let Asterisk = () =>
<span className="margin-right red">*</span>

const FundingOrganizationForm = ({form, fields, validation, changeCallback, submitCallback, cancelCallback, loading, message, dismissMessage}) =>
<div>
  <Spinner message="Loading..." visible={loading} />

  <Grid>
    <Row>
      { message.ERROR && <Alert bsStyle="danger" onDismiss={dismissMessage}>{message.ERROR}</Alert> }
      { message.SUCCESS && <Alert bsStyle="success" onDismiss={dismissMessage}>{message.SUCCESS}</Alert> }
    </Row>

    <Row className="bordered padding-top margin-bottom">
      <Form inline>
        <Col md={6} className="margin-bottom">
          <FormGroup controlId="selectPartner" bsSize="small" validationState={validation.partner === false ? 'error' : null}>
            <ControlLabel className="margin-right">Partner <Asterisk /></ControlLabel>
            <FormControl
              componentClass="select"
              placeholder="Select Partner Organization"
              value={form.partner}
              onChange={event => changeCallback('partner', event.target['value'])}>
              <option className="disabled" key={0} hidden>Select a Partner</option>
              {
                fields.partners.map((field, index) =>
                  <option key={`${index}_${field.value}`} value={field.value}>
                    {field.label}
                  </option>
                )
              }
            </FormControl>
            { validation.partner === false && <HelpBlock>This field is required.</HelpBlock> }
          </FormGroup>
        </Col>

        <Col md={6} className="margin-bottom">
          <Row className="m-t-3">

            <Col md={4}>
              <ControlLabel className="margin-right">Member Type <Asterisk /></ControlLabel>
            </Col>

            <Col md={3}>
              <Radio
                name="memberType"
                value="Partner"
                checked={form.memberType === 'Partner'}
                onChange={event => changeCallback(event.target['name'], event.target['value'])}
                inline>
                Partner
              </Radio>
            </Col>

            <Col md={3}>
              <Radio
                name="memberType"
                value="Associate"
                checked={form.memberType === 'Associate'}
                onChange={event => changeCallback(event.target['name'], event.target['value'])}
                inline>
                Associate
              </Radio>
            </Col>
          </Row>
          { validation.memberType === false && <HelpBlock>This field is required.</HelpBlock> }

        </Col>
      </Form>
    </Row>

    <Row>
      <Col md={6} className="margin-bottom">
        <FormGroup bsSize="small" validationState={validation.name === false ? 'error' : null}>
          <ControlLabel className="margin-right">Name <Asterisk /></ControlLabel>
          <FormControl
            type="text"
            value={form.name}
            maxLength={100}
            onChange={event => changeCallback('name', event.target['value'])}
            placeholder="Enter name of funding organization"
          />
          <FormControl.Feedback />
          { validation.name === false && <HelpBlock>This field is required.</HelpBlock> }
        </FormGroup>
      </Col>

      <Col md={6} className="margin-bottom">
        <FormGroup bsSize="small" validationState={validation.abbreviation === false ? 'error' : null}>
          <ControlLabel className="margin-right">Abbreviation <Asterisk /></ControlLabel>
          <FormControl
            type="text"
            value={form.abbreviation}
            maxLength={15}
            onChange={event => changeCallback('abbreviation', event.target['value'])}
            placeholder="Enter abbreviation for funding organization" />
          <FormControl.Feedback />
          { validation.abbreviation === false && <HelpBlock>This field is required.</HelpBlock> }
        </FormGroup>
      </Col>
    </Row>


    <Row>
      <Col md={6} className="margin-bottom">
          <FormGroup controlId="selectOrganizationType" bsSize="small" validationState={validation.organizationType === false ? 'error' : null}>
            <ControlLabel className="margin-right">Organization Type <Asterisk /></ControlLabel>
            <FormControl
              componentClass="select"
              placeholder="Select Partner Organization Type"
              value={form.organizationType}
              onChange={event => changeCallback('organizationType', event.target['value'])}>
              <option className="disabled" key={0} hidden>Select organization type</option>
              {
                fields.organizationTypes.map((field, index) =>
                  <option key={`${index}_${field}`} value={field}>
                    {field}
                  </option>
                )
              }
            </FormControl>
            { validation.organizationType === false && <HelpBlock>This field is required.</HelpBlock> }
        </FormGroup>

      </Col>

      <Col md={6} className="margin-bottom">

        <FormGroup bsSize="small" validationState={validation.mapCoordinates === false ? 'error' : null}>
          <ControlLabel className="margin-right">Map Coordinates</ControlLabel>
          <FormControl
            type="text"
            value={form.mapCoordinates}
            maxLength={50}
            onChange={event => changeCallback('mapCoordinates', event.target['value'])}
            placeholder="Enter map coordinates" />
          <FormControl.Feedback />
          { validation.mapCoordinates === false && <HelpBlock>This field is required.</HelpBlock> }
        </FormGroup>

      </Col>
    </Row>

    <Row>
      <Col md={6} className="margin-bottom">
        <FormGroup controlId="selectCountry" bsSize="small" validationState={validation.country === false ? 'error' : null}>
          <ControlLabel className="margin-right">Country <Asterisk /></ControlLabel>
          <FormControl
            componentClass="select"
            placeholder="Select a Country"
            value={form.country}
            onChange={event => changeCallback('country', event.target['value'])}>
            <option className="disabled" key={0} hidden>Select a country</option>
            {
              fields.countries.map((field, index) =>
                <option key={`${index}_${field.value}`} value={field.value}>
                  {field.label}
                </option>
              )
            }
          </FormControl>
        { validation.country === false && <HelpBlock>This field is required.</HelpBlock> }
        </FormGroup>
      </Col>

      <Col md={6} className="margin-bottom">
        <FormGroup controlId="selectCurrency" bsSize="small" validationState={validation.currency === false ? 'error' : null}>
          <ControlLabel className="margin-right">Currency <Asterisk /></ControlLabel>
          <FormControl
            componentClass="select"
            placeholder="Select Currency Type"
            value={form.currency}
            onChange={event => changeCallback('currency', event.target['value'])}>
            <option className="disabled" key={0} hidden>Select a currency</option>
            {
              fields.currencies.map((field, index) =>
                <option key={`${index}_${field.value}`} value={field.value}>
                  {field.label}
                </option>
              )
            }
          </FormControl>
          { validation.currency === false && <HelpBlock>This field is required.</HelpBlock> }
        </FormGroup>
      </Col>
    </Row>

    <FormGroup bsSize="small">
      <ControlLabel className="margin-right">Note</ControlLabel>
      <FormControl
        componentClass="textarea"
        placeholder="Enter notes"
        maxLength={8000}
        value={form.note}
        onChange={event => changeCallback('note', event.target['value'])}
      />
    </FormGroup>

    <FormGroup bsSize="small">
      <Checkbox
        checked={form.annualizedFunding}
        onChange={event => changeCallback('annualizedFunding', event.target['checked'])}>
        <b>Annualized Funding</b>
      </Checkbox>
    </FormGroup>


    <div className="text-center">
      <Button bsStyle="primary" className="margin-right" onClick={submitCallback}>Save</Button>
      <Button onClick={cancelCallback}>Cancel</Button>
    </div>

  </Grid>
</div>

export default FundingOrganizationForm;
